spring.application.name=shopCRUD
server.port=8081


# CONFIGURACIÓN DE LA BASE DE DATOS
spring.datasource.url=jdbc:mysql://localhost:3306/SalesDB_in5bv?useSSL=false&serverTimezone=UTC
spring.datasource.username=IN5BV
spring.datasource.password=_@miNdAa5V
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Esto actualiza las tablas automáticamente si hay cambios en los Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.output.ansi.enabled=ALWAYS
spring.banner.charset=UTF-8